name: Run-Proselint
run-name: ${{ github.actor }} is running Proselint 
on: [push]

jobs:
  proselint:
    name: Proselint 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo add-apt-repository universe
      - run: sudo apt install python3-proselint
      - run: find . -name '*.md' | xargs proselint
